### ISSUE TITLE
gzip: stdin: not in gzip format

### ISSUE THREAD

**Issue by KeyLD** [haiwen/seafile-server-installer-cn#21]
centos7 安装6.0.9 下使用脚本安装一直卡在这里，解压文件失败

已尝试: <br>
1. 修改脚本 tar -xvf 安装
2. 升级tar到1.29版本安装
3. 官网下载文件到/opt/目录方法皆无效

然而在自己的机子上测试解压是可以的，这是怎么回事？？

**Comment by believe0815** [comment]
将脚本:
SEAFILE_SERVER_PACKAGE_URL=http://download-cn.seafile.com/${SEAFILE_SERVER_PACKAGE}
改为:
SEAFILE_SERVER_PACKAGE_URL=https://bintray.com/artifact/download/seafile-org/seafile/${SEAFILE_SERVER_PACKAGE}

已测试

**Comment by believe0815** [comment]
bash seafile-server-centos-7-amd64-http 6.0.9

**Comment by ghost** [comment]
将脚本中的:
SEAFILE_SERVER_PACKAGE_URL=http://download-cn.seafile.com/${SEAFILE_SERVER_PACKAGE}
改为:
SEAFILE_SERVER_PACKAGE_URL=https://bintray.com/artifact/download/seafile-org/seafile/${SEAFILE_SERVER_PACKAGE}
然后:
bash seafile-server-centos-7-amd64-http 6.0.9

已测试

**Comment by Xue-JW** [comment]
Ubuntu 16.04,我的解决方式是把下载好的安装包放入/opt/目录中,留意版本号
按官方步骤执行:
wget https://raw.githubusercontent.com/haiwen/seafile-server-installer-cn/master/seafile-server-ubuntu-16-04-amd64-http
再执行:
bash seafile-server-centos-7-amd64-http <版本号>
即可,官方脚本检测到opt目录下有对应安装包不从网上下载直接安装就没问题了
