### ISSUE TITLE
安装过程中异常退出

### ISSUE THREAD

**Issue by sincerefly** [haiwen/seafile-server-installer-cn#26]
异常退出，如下：

> Created symlink from /etc/systemd/system/multi-user.target.wants/mariadb.service to /usr/lib/systemd/system/mariadb.service.
Created symlink from /etc/systemd/system/multi-user.target.wants/seafile.service to /etc/systemd/system/seafile.service.
Created symlink from /etc/systemd/system/multi-user.target.wants/seahub.service to /etc/systemd/system/seahub.service.
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   159    0   159    0     0     94      0 --:--:--  0:00:01 --:--:--    94
gzip: stdin: not in gzip format
tar: Child returned status 1
tar: Error is not recoverable: exiting now

**Comment by sincerefly** [comment]
http://download-cn.seafile.com/

这个网站访问不了了...

**Comment by sincerefly** [comment]
修改了部分脚本，手动下载了安装包，问题解决

**Comment by ScarleX1010** [comment]
可以问一下如何手动下载安装包 谢谢
