### ISSUE TITLE
我用VPS纯净14.04安装出现tar错误

### ISSUE THREAD

**Issue by sunchao1984** [haiwen/seafile-server-installer-cn#33]
gzip: stdin: not in gzip format
tar: Child returned status 1
tar: Error is not recoverable: exiting now

显示不是一个gzip文件，请问这个如何解决？

另外提供一个其他问题的解决方案：安装jdk8的时候提示Unable to locate package，需要刷新源
刷新的方法如下：
sudo apt-get install software-properties-common python-software-properties
sudo add-apt-repository ppa:openjdk-r/ppa
sudo apt-get update

**Comment by itsmingjie** [comment]
Duplicate #21
