### ISSUE TITLE
使用一键安装的脚本安装专业版不成功

### ISSUE THREAD

**Issue by EGQM** [haiwen/seafile-server-installer-cn#43]
多次尝试使用腾讯云纯净的ubuntu16.04，一键安装的脚本安装专业版（seafile-pro-server_6.1.8_x86-64.tar.gz），不成功。
 安装过程输出如下信息：

Seahub_ is started

Done.

Seahub is not running
Done.

Stopping seafile server ...
Done.
Starting productive Seafile server
Job for seafile-server.service failed because the control process exited with error code. See "systemctl status seafile-server.service" and "journalctl -xe" for details.

执行systemctl status seafile-server.service后，输出为：
seafile-server.service - LSB: Seafile server
   Loaded: loaded (/etc/init.d/seafile-server; bad; vendor preset: enabled)
   Active: failed (Result: exit-code) since Mon 2018-05-21 23:23:20 CST; 26s ago
     Docs: man:systemd-sysv-generator(8)
  Process: 11353 ExecStart=/etc/init.d/seafile-server start (code=exited, status=1/FAILURE)
    Tasks: 92
   Memory: 326.4M
      CPU: 8.331s
   CGroup: /system.slice/seafile-server.service
           ├─11382 /opt/seafile/seafile-pro-server-6.1.8/seafile/bin/seafile-controller -c /opt/seafile/ccnet -d /opt/seafi
           ├─11385 ccnet-server -F /opt/seafile/conf -c /opt/seafile/ccnet -f /opt/seafile/logs/ccnet.log -d -L /opt/seafil
           ├─11387 /usr/bin/python2.7 -m seafevents.main --config-file /opt/seafile/conf/seafevents.conf --loglevel debug -
           ├─11388 /usr/bin/python2.7 -m wsgidav.server.run_server runfcgi --log-file /opt/seafile/logs/seafdav.log --pid /
           ├─11389 /usr/bin/java -Xms256m -Xmx1g -Djava.awt.headless=true -XX:+UseParNewGC -XX:+UseConcMarkSweepGC -XX:CMSI
           └─11394 seaf-server -F /opt/seafile/conf -c /opt/seafile/ccnet -d /opt/seafile/seafile-data -l /opt/seafile/logs

May 21 23:23:11 VM-136-74-ubuntu systemd[1]: Starting LSB: Seafile server...
May 21 23:23:12 VM-136-74-ubuntu seafile-server[11353]: ** Message: seafile-controller.c(1088): loading seafdav config from
May 21 23:23:12 VM-136-74-ubuntu seafile-server[11353]: License file /opt/seafile/seafile-license.txt does not exist, allow
May 21 23:23:12 VM-136-74-ubuntu seafile-server[11353]: ** Message: seafile-controller.c(1088): loading seafdav config from
May 21 23:23:12 VM-136-74-ubuntu seafile-server[11353]: License file /opt/seafile/seafile-license.txt does not exist, allow
May 21 23:23:20 VM-136-74-ubuntu systemd[1]: seafile-server.service: Control process exited, code=exited status=1
May 21 23:23:20 VM-136-74-ubuntu systemd[1]: Failed to start LSB: Seafile server.
May 21 23:23:20 VM-136-74-ubuntu systemd[1]: seafile-server.service: Unit entered failed state.
May 21 23:23:20 VM-136-74-ubuntu systemd[1]: seafile-server.service: Failed with result 'exit-code'.

如何解决这个问题？

**Comment by ldm0** [comment]
Actually I solved this problem by using:
yum install selinux-policy-targeted

**Comment by renfeipeng** [comment]
这个阶段是安装过程完成后最后一次重启，这里的报错可以忽略，因为seafile是部署完成的。碰到这种情况手动重启一下服务就行了。
