### ISSUE TITLE
Job for seahub.service failed

### ISSUE THREAD

**Issue by Michae1G** [haiwen/seafile-server-installer-cn#60]
centos 7    安装过程，在开机启动时出错。不打印 账号，需要手动 重设admin账号， 但是登录后无法上传下载。  不知道 是不是后续的脚本设置 没完成。。。。
----------------------------------------
Successfully created seafile admin
----------------------------------------

Seahub is started
Done.
Seahub is not running
Done.
Stopping seafile server ...
Done.
### **Job for seahub.service failed because the control process exited with error code. See "systemctl status seahub.service" and "journalctl -xe" for details.**
-------------------------------------------------------------------------------------------------------------------
[root@localhost ~]# **systemctl status seahub.service**
● seahub.service - Seafile Seahub
   Loaded: loaded (/etc/systemd/system/seahub.service; enabled; vendor preset: disabled)
   Active: failed (**Result: exit-code**) since 二 2019-02-19 22:25:55 CST; 14min ago
  Process: 21044 ExecStart=/opt/seafile/seafile-server-latest/seahub.sh start 8000 (code=exited, status=1/FAILURE)
 Main PID: 21044 (code=exited, status=1/FAILURE)
2月 19 22:25:55 localhost.localdomain systemd[1]: Starting Seafile Seahub...
2月 19 22:25:55 localhost.localdomain seahub.sh[21044]: LC_ALL is not set in ENV, set to en_US.UTF-8
2月 19 22:25:55 localhost.localdomain seahub.sh[21044]: Seahub is already running.
2月 19 22:25:55 localhost.localdomain systemd[1]: **seahub.service: main process exited, code=exited,** status=1/FAILURE
2月 19 22:25:55 localhost.localdomain systemd[1]: Failed to start Seafile Seahub.
2月 19 22:25:55 localhost.localdomain systemd[1]: Unit seahub.service entered failed state.
2月 19 22:25:55 localhost.localdomain systemd[1]: seahub.service failed.
-------------------------------------------------------------------------------------------------------------------
[root@localhost ~]# journalctl -xe
2月 19 22:25:52 localhost.localdomain seafile-control[20959]: seafile-controller.c(1155): loading seafdav config from /opt/seafile/conf/seafdav.conf
2月 19 22:25:52 localhost.localdomain seafile.sh[20935]: [02/19/19 22:25:52] ../common/session.c(139): using config file /opt/seafile/conf/ccnet.conf
2月 19 22:25:52 localhost.localdomain seafile.sh[20935]: [02/19/19 22:25:52] ../common/license.c(406): Loading license file /opt/seafile/seafile-license.txt ..
2月 19 22:25:52 localhost.localdomain seafile.sh[20935]: [02/19/19 22:25:52] ../common/license.c(409): License file /opt/seafile/seafile-license.txt does not exist, allow at most 3 tr
2月 19 22:25:52 localhost.localdomain seafile.sh[20935]: License file /opt/seafile/seafile-license.txt does not exist, allow at most 3 trial users
2月 19 22:25:52 localhost.localdomain seafile.sh[20935]: Starting seafile server, please wait ...
2月 19 22:25:52 localhost.localdomain seafile-control[20965]: seafile-controller.c(1155): loading seafdav config from /opt/seafile/conf/seafdav.conf
2月 19 22:25:55 localhost.localdomain seafile.sh[20935]: Seafile server started
2月 19 22:25:55 localhost.localdomain seafile.sh[20935]: Done.
2月 19 22:25:55 localhost.localdomain systemd[1]: Started Seafile Server.
-- Subject: Unit seafile.service has finished start-up
-- Defined-By: systemd
-- Support: http://lists.freedesktop.org/mailman/listinfo/systemd-devel
-- 
-- Unit seafile.service has finished starting up.
-- 
-- The start-up result is done.
2月 19 22:25:55 localhost.localdomain polkitd[3993]: Unregistered Authentication Agent for unix-process:20928:244754 (system bus name :1.56, object path /org/freedesktop/PolicyKit1/Au
2月 19 22:25:55 localhost.localdomain polkitd[3993]: Registered Authentication Agent for unix-process:21038:245083 (system bus name :1.57 [/usr/bin/pkttyagent --notify-fd 5 --fallback
2月 19 22:25:55 localhost.localdomain systemd[1]: Starting Seafile Seahub...
-- Subject: Unit seahub.service has begun start-up
-- Defined-By: systemd
-- Support: http://lists.freedesktop.org/mailman/listinfo/systemd-devel
-- 
-- Unit seahub.service has begun starting up.
2月 19 22:25:55 localhost.localdomain seahub.sh[21044]: LC_ALL is not set in ENV, set to en_US.UTF-8
2月 19 22:25:55 localhost.localdomain seahub.sh[21044]: Seahub is already running.
2月 19 22:25:55 localhost.localdomain systemd[1]: **seahub.service: main process exited, code=exited, status=1/FAILURE**
2月 19 22:25:55 localhost.localdomain systemd[1]: Failed to start Seafile Seahub.
-- Subject: Unit seahub.service has failed
-- Defined-By: systemd
-- Support: http://lists.freedesktop.org/mailman/listinfo/systemd-devel
-- 
-- Unit seahub.service has failed.
-- 
-- The result is failed.
2月 19 22:25:55 localhost.localdomain systemd[1]: Unit seahub.service entered failed state.
2月 19 22:25:55 localhost.localdomain systemd[1]: seahub.service failed.
2月 19 22:25:55 localhost.localdomain polkitd[3993]: Unregistered Authentication Agent for unix-process:21038:245083 (system bus name :1.57, object path /org/freedesktop/PolicyKit1/Au
2月 19 22:28:43 localhost.localdomain polkitd[3993]: Registered Authentication Agent for unix-process:21124:261821 (system bus name :1.60 [/usr/bin/pkttyagent --notify-fd 5 --fallback
2月 19 22:28:43 localhost.localdomain systemd[1]: Stopping firewalld - dynamic firewall daemon...
-- Subject: Unit firewalld.service has begun shutting down
-- Defined-By: systemd
-- Support: http://lists.freedesktop.org/mailman/listinfo/systemd-devel
-- 
-- Unit firewalld.service has begun shutting down.
2月 19 22:28:44 localhost.localdomain kernel: Ebtables v2.0 unregistered
2月 19 22:28:44 localhost.localdomain systemd[1]: Stopped firewalld - dynamic firewall daemon.
-- Subject: Unit firewalld.service has finished shutting down
-- Defined-By: systemd
-- Support: http://lists.freedesktop.org/mailman/listinfo/systemd-devel
-- 
-- Unit firewalld.service has finished shutting down.
2月 19 22:28:44 localhost.localdomain systemd[1]: Starting firewalld - dynamic firewall daemon...
-- Subject: Unit firewalld.service has begun start-up
-- Defined-By: systemd
-- Support: http://lists.freedesktop.org/mailman/listinfo/systemd-devel
-- 
-- Unit firewalld.service has begun starting up.
2月 19 22:28:45 localhost.localdomain systemd[1]: Started firewalld - dynamic firewall daemon.
-- Subject: Unit firewalld.service has finished start-up
-- Defined-By: systemd
-- Support: http://lists.freedesktop.org/mailman/listinfo/systemd-devel
-- 
-- Unit firewalld.service has finished starting up.
-- 
-- The start-up result is done.
2月 19 22:28:45 localhost.localdomain polkitd[3993]: Unregistered Authentication Agent for unix-process:21124:261821 (system bus name :1.60, object path /org/freedesktop/PolicyKit1/Au
2月 19 22:28:45 localhost.localdomain kernel: ip_tables: (C) 2000-2006 Netfilter Core Team
2月 19 22:28:45 localhost.localdomain kernel: ip6_tables: (C) 2000-2006 Netfilter Core Team
2月 19 22:28:45 localhost.localdomain kernel: Ebtables v2.0 registered

**Comment by AshiakerWang** [comment]
same issue here, have you found any solutions?
