### ISSUE TITLE
请问下内网端口号是多少呢？需要做端口映射，8000,和80都试过不对。

### ISSUE THREAD

**Issue by dudt** [haiwen/seafile-server-installer-cn#67]
请问下内网端口号是多少呢？需要做端口映射，8000,和80都试过不对。

**Comment by Fr33raNg3r** [comment]
先试试本地能访问不，能访问则是因为防火墙的关系，不能访问则是因为Nginx的关系。
默认是80，可以从后台设置中看到的8000是本地监听端口，但大陆运营商是关闭了80和443端口的。
