### ISSUE TITLE
使用此脚本安装最新的5.0.0后，安装过程一切正常，也显示安装成功，最后地址打开，显示如下

### ISSUE THREAD

**Issue by xu-xiang** [haiwen/seafile-server-installer-cn#9]
502 Bad Gateway

nginx/1.4.6 (Ubuntu)

**Comment by xu-xiang** [comment]
help help T T

**Comment by freeplant** [comment]
这个安装脚本是针对 5.0 以下版本的。还没有加入对 5.0 版本的支持。

**Comment by JoeLucky** [comment]
Checking for java ...Done.


localhost.local is not a valid name
 
然后退出了 centos7.0 + seafile6.0.4

官方没有5.0以下的pro版本啊？
